-USE ROLE ACCOUNTADMIN;

-- Create Database and Schemas to separate DEV, PRE y PROD
CREATE DATABASE IF NOT EXISTS BANANA_QUALITY;
USE DATABASE BANANA_QUALITY;
CREATE SCHEMA IF NOT EXISTS DEV;

DROP SCHEMA BANANA_QUALITY.PUBLIC;