USE ROLE ACCOUNTADMIN;

-- Create Database and Schemas to separate DEV, PRE y PROD
CREATE DATABASE IF NOT EXISTS BANANA_QUALITY;
USE DATABASE BANANA_QUALITY;
CREATE SCHEMA IF NOT EXISTS DEV;

CREATE STAGE BANANA_QUALITY.DEV.RAW_DATA;
CREATE STAGE BANANA_QUALITY.DEV.ML_MODELS;

DROP SCHEMA BANANA_QUALITY.PUBLIC;