USE ROLE ACCOUNTADMIN;

-- Create Database and Schemas to separate processing, execution, and deployment
CREATE DATABASE IF NOT EXISTS BANANA_QUALITY;
USE DATABASE BANANA_QUALITY;
CREATE SCHEMA IF NOT EXISTS FEATURE_ENGINEERING;
CREATE SCHEMA IF NOT EXISTS ML_ENGINEERING;

DROP SCHEMA BANANA_QUALITY.PUBLIC;