USE ROLE ACCOUNTADMIN;

-- Create Database and Schemas to separate processing, execution, and deployment
CREATE DATABASE IF NOT EXISTS DEMO_GITHUB_ACTIONS;
USE DATABASE DEMO_GITHUB_ACTIONS;
CREATE SCHEMA IF NOT EXISTS PROD;
CREATE SCHEMA IF NOT EXISTS PRE;
CREATE SCHEMA IF NOT EXISTS DEV;
USE SCHEM PROD;
CREATE STAGE IF NOT EXISTS PYTHON_FILES;
USE SCHEM PRE;
CREATE STAGE IF NOT EXISTS PYTHON_FILES;
USE SCHEM DEV;
CREATE STAGE IF NOT EXISTS PYTHON_FILES;

DROP SCHEMA DEMO_GITHUB_ACTIONS.PUBLIC;