USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE BANANA_QUALITY;

CREATE OR REPLACE TASK DEV.TASK_PROCESS
WAREHOUSE = COMPUTE_WH
SCHEDULE = '3 MINUTE'
AS
    CALL BANANA_QUALITY.DEV.process_step();

CREATE OR REPLACE TASK DEV.TASK_TRAIN
WAREHOUSE = COMPUTE_WH
AFTER DEV.TASK_PROCESS
AS
    CALL BANANA_QUALITY.DEV.train_step();
;

CREATE OR REPLACE TASK DEV.TASK_REGISTRY
WAREHOUSE = COMPUTE_WH
AFTER DEV.TASK_TRAIN
AS
    CALL BANANA_QUALITY.DEV.registry_step();
;

ALTER TASK DEV.TASK_PROCESS RESUME;
ALTER TASK DEV.TASK_TRAIN RESUME;
ALTER TASK DEV.TASK_REGISTRY RESUME;


-- Task individual
--CREATE OR REPLACE TASK DEV.TASK_TRAIN_2
--WAREHOUSE = COMPUTE_WH
--AS
--    CALL BANANA_QUALITY.DEV.train_step();
--;

--EXECUTE TASK TASK_TRAIN_2;



