USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS BANANA_QUALITY;
USE DATABASE BANANA_QUALITY;
CREATE SCHEMA IF NOT EXISTS EXP;
USE SCHEMA EXP;

CREATE STAGE BANANA_QUALITY.EXP.RAW_DATA;
CREATE STAGE BANANA_QUALITY.EXP.ML_MODELS;

DROP SCHEMA BANANA_QUALITY.PUBLIC;