USE ROLE $ROLE$;
USE WAREHOUSE $WAREHOUSE$;

CREATE DATABASE IF NOT EXISTS $DB_NAME$;
USE DATABASE $DB_NAME$;
CREATE SCHEMA IF NOT EXISTS $SCHEMA$;
USE SCHEMA $SCHEMA$;

CREATE STAGE $DB_NAME$.$SCHEMA$.RAW_DATA;
CREATE STAGE $DB_NAME$.$SCHEMA$.ML_MODELS;

DROP SCHEMA $DB_NAME$.PUBLIC;