USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS BANANA_QUALITY;
USE DATABASE BANANA_QUALITY;
DROP SCHEMA BANANA_QUALITY.PUBLIC;

-- DEFINE EXP SCHEMA OBJECTS
CREATE SCHEMA IF NOT EXISTS EXP;
USE SCHEMA EXP;

CREATE STAGE BANANA_QUALITY.EXP.RAW_DATA;
CREATE STAGE BANANA_QUALITY.EXP.ML_MODELS;


-- DEFINE VALIDATE SCHEMA OBJECTS
CREATE SCHEMA IF NOT EXISTS VALIDATE;
USE SCHEMA VALIDATE;

CREATE STAGE BANANA_QUALITY.VALIDATE.RAW_DATA;
CREATE STAGE BANANA_QUALITY.VALIDATE.ML_MODELS;

-- DEFINE VALIDATE SCHEMA OBJECTS
CREATE SCHEMA IF NOT EXISTS LIVE;
USE SCHEMA LIVE;

CREATE STAGE BANANA_QUALITY.LIVE.RAW_DATA;
CREATE STAGE BANANA_QUALITY.LIVE.ML_MODELS;
