USE ROLE '${SNOWSQL_ROLE}';

-- Create Database and Schemas to separate processing, execution, and deployment
CREATE DATABASE IF NOT EXISTS {{SNOWSQL_DATABASE}};
USE DATABASE {{SNOWSQL_DATABASE}};
--CREATE SCHEMA IF NOT EXISTS PROD;
--CREATE SCHEMA IF NOT EXISTS PRE;
CREATE SCHEMA IF NOT EXISTS {{SNOWFLAKE_SCHEMA_DEV}};
--USE SCHEMA PROD;
--CREATE STAGE IF NOT EXISTS PYTHON_FILES;
--USE SCHEMA PRE;
--CREATE STAGE IF NOT EXISTS PYTHON_FILES;
USE SCHEMA {{SNOWFLAKE_SCHEMA_DEV}};
CREATE STAGE IF NOT EXISTS PYTHON_FILES;

--DROP SCHEMA DEMO_GITHUB_ACTIONS.PUBLIC;